## NumPy

 - is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
 
    
  - is a linear algebra library for Python that is so important for Data Science for the reason that almost all libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
  
  
  - NumPy is already included in the Anaconda Distribution

## Numpy Array through casting a List

In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4]

In [3]:
array_1 = np.array(list_1)

In [4]:
array_1

array([1, 2, 3, 4])

In [5]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.arange

     - return evenly spaced values within a given interval

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### np.zeros

     - return a new array of given shape and type, filled with zeros

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### np.ones

     - return a new array of given shape and type, filled with ones

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.linspace

    - return evenly spaced numbers over a specified interval

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

### np.eye

    - return a 2-D array with ones on the diagonal and zeros elsewhere

In [16]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### np.random.rand

    - return values (random) in a given shape

In [17]:
np.random.rand(5)

array([0.67667495, 0.50323931, 0.25030322, 0.17335859, 0.18726634])

In [18]:
np.random.rand(2,3)

array([[0.96628257, 0.42846521, 0.54507323],
       [0.04570476, 0.10953892, 0.5688092 ]])

### np.random.randn

    - return a sample (or samples) from the 'standard normal' distribution

In [19]:
np.random.randn(5,5)

array([[-0.46071553,  0.23529599, -1.77461392, -0.17827244,  0.74779135],
       [-0.37522057,  0.78928125,  1.6960572 , -2.17453626, -0.33419323],
       [-0.60041077,  0.33216144,  0.46220126,  0.69257299,  2.48523126],
       [-0.59713804, -0.73299069,  0.54758508,  1.94117102, -1.3934629 ],
       [ 0.10001418,  0.68420583, -0.22256475,  0.28471177,  0.40244734]])

### np.random.randint

     - return random integers from low (inclusive) to high (exclusive)

In [20]:
np.random.randint(1,20) #generate a random number from 1 to 19

13

In [21]:
np.random.randint(1,10,5) #generate five random numbers from 1 to 9 (discrete uniform distribution)

array([3, 5, 7, 7, 6])

### np.reshape

    - gives a new shape to an array without changing its data

In [22]:
random_array = np.random.randint(0,50,25)

In [23]:
random_array

array([ 5, 23, 13, 24, 22,  7, 42, 36, 11, 10, 40, 43, 28, 27, 19, 29, 20,
       45, 47,  7, 17, 24, 27, 17, 16])

In [24]:
random_array.reshape(5,5)

array([[ 5, 23, 13, 24, 22],
       [ 7, 42, 36, 11, 10],
       [40, 43, 28, 27, 19],
       [29, 20, 45, 47,  7],
       [17, 24, 27, 17, 16]])

## Array Methods

### max(), min()

    - identify what is the max (highest) and min (lowest) value

In [25]:
random_array = np.random.randint(0,25,10)

In [26]:
random_array

array([21,  2, 21, 19,  8, 16, 18, 24, 15, 22])

In [27]:
random_array.max()

24

In [28]:
random_array.min()

2

### argmax(), argmin()

      - identify index of max and min values

In [29]:
random_array = np.random.randint(0,25,10)

In [30]:
random_array

array([19, 18,  4,  8, 10,  4, 14, 19, 19, 13])

In [31]:
random_array.argmax()

0

In [32]:
random_array.argmin()

2

### shape()

    - identify the shape of a vector

In [33]:
random_array = np.random.randint(0,25,10)

In [34]:
random_array.shape

(10,)

In [35]:
new_arr = random_array.reshape(2,5)

In [36]:
new_arr

array([[10, 14,  0,  5, 22],
       [20, 15,  4, 10,  8]])

In [37]:
new_arr.shape

(2, 5)

### dtype

    - identify data type of array

In [38]:
new_arr.dtype

dtype('int32')