In [2]:
import numpy as np

## More Numpy Matrix Multiplications

In [3]:
a = np.array([2,3,-5,4]).reshape(2,2)
b = np.array([3,-2,1,6]).reshape(2,2)

In [4]:
a

array([[ 2,  3],
       [-5,  4]])

In [5]:
b

array([[ 3, -2],
       [ 1,  6]])

In [6]:
np.dot(a,b)

array([[  9,  14],
       [-11,  34]])

In [7]:
np.multiply(a,b) # this is different, multiplication element wise only

array([[ 6, -6],
       [-5, 24]])

In [8]:
np.matmul(a,b)

array([[  9,  14],
       [-11,  34]])

In [9]:
c = np.array([2,3,1,2,-7,4]).reshape(2,3)
d = np.array([3,4,5,1,1,4,2,1,4]).reshape(3,3)

In [10]:
c

array([[ 2,  3,  1],
       [ 2, -7,  4]])

In [11]:
d

array([[3, 4, 5],
       [1, 1, 4],
       [2, 1, 4]])

In [12]:
np.dot(c,d)

array([[11, 12, 26],
       [ 7,  5, -2]])

## Transpose of a Matrix

- In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by: $ A^T $

In [13]:
matrix_t = np.array([1,2,3,4]).reshape(2,2)

In [15]:
np.transpose(matrix_t)

array([[1, 3],
       [2, 4]])

In [16]:
matrix_f = np.arange(1,7).reshape(2,3)

In [17]:
matrix_f

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.transpose(matrix_f)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Determinant

- In linear algebra, the determinant is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the linear transformation described by the matrix. The determinant of a matrix A is denoted det(A), det A, or |A|.

In [20]:
det_a = np.arange(1,5).reshape(2,2)

In [21]:
det_a

array([[1, 2],
       [3, 4]])

In [22]:
np.linalg.det(det_a)

-2.0000000000000004

In [23]:
det_b = np.array([5,3,7,2,-5,8,-6,4,9]).reshape(3,3)

In [24]:
det_b

array([[ 5,  3,  7],
       [ 2, -5,  8],
       [-6,  4,  9]])

In [25]:
np.linalg.det(det_b)

-736.9999999999999

## Inverse of a Matrix

- The concept of inverse of a matrix is a multidimensional generalization of the concept of reciprocal of a number: the product between a number and its reciprocal is equal to 1; the product between a square matrix and its inverse is equal to the identity matrix.

In [34]:
orig_a = np.array([2,5,1,3]).reshape(2,2)

In [35]:
inv_a = np.linalg.inv(orig_a)

In [36]:
new_matrix = np.dot(orig_a, inv_a)

In [37]:
new_matrix

array([[1., 0.],
       [0., 1.]])

In [39]:
# 3x3 Matrix

matrix_3 = np.array([2,-1,0,0,1,2,1,1,0]).reshape(3,3)

In [40]:
matrix_3

array([[ 2, -1,  0],
       [ 0,  1,  2],
       [ 1,  1,  0]])

In [41]:
np.linalg.inv(matrix_3)

array([[ 0.33333333,  0.        ,  0.33333333],
       [-0.33333333,  0.        ,  0.66666667],
       [ 0.16666667,  0.5       , -0.33333333]])