## Numpy Array Indexing and Selection

In [1]:
import numpy as np

In [2]:
new_arr = np.arange(0,16)

In [3]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
new_arr[9]

9

In [5]:
new_arr[1:6]

array([1, 2, 3, 4, 5])

In [6]:
new_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
new_arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
new_arr[:7] = 100 # NumPy arrays has the ability to broadcast

In [9]:
new_arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [10]:
lst = [1,2,3,4,5]

In [11]:
lst[0:3] = 100 # list cannot broadcast

TypeError: can only assign an iterable

## Indexing a 2-D Array (Matrix)

In [ ]:
array_2D = np.array([2,4,6,8,10,12,14,16,18])

In [ ]:
array_2D

In [ ]:
array_2D = array_2D.reshape(3,3)

In [ ]:
array_2D

In [ ]:
# grab the value of 2

array_2D[0,0]

In [ ]:
# grab the first row

array_2D[0]

In [ ]:
# grab the value of 16

array_2D[2,1]

In [ ]:
# selecting sub-matrices

# [4, 6]
# [10, 12]

array_2D

In [ ]:
array_2D[:2,1:]

In [ ]:
# selecting sub-matrices

# [8, 10]
# [14, 16]

In [ ]:
array_2D[1:,:2]

In [ ]:
# selecting sub-matrices

# [4, 6]
# [10, 12]
# [16, 18]

array_2D

In [ ]:
array_2D[:,1:]

In [ ]:
# selecting sub-matrices

# [8, 10, 12]
# [14, 16, 18]

array_2D

In [ ]:
array_2D[1:,:]

In [ ]:
big_2D_array = np.arange(50).reshape(5,10)

In [ ]:
big_2D_array

In [ ]:
big_2D_array[2:4,3:8]

## Conditional Selection

In [ ]:
another_array = np.arange(1,16)

In [ ]:
another_array

In [ ]:
another_array > 5

In [ ]:
bool_array = another_array > 5

In [ ]:
bool_array

In [ ]:
another_array[bool_array]

In [ ]:
another_array[another_array > 5]

## Matrix Operations

   - addition
   - subtraction
   - scalar multiplication, matrix multiplication, dot
   - division (there is no such thing!)
   
   
$ a = \begin{bmatrix} 3 & -4 \\ 8 & 5 \end{bmatrix}$

$ b = \begin{bmatrix} 9 & -5 \\ 2 & 6 \end{bmatrix}$

$ c = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9\end{bmatrix}$

$ x = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

$ y = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$

In [ ]:
a = np.array([3,-4,8,5]).reshape(2,2)
b = np.array([9,-5,2,-6]).reshape(2,2)
c = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [ ]:
a

In [ ]:
b

In [ ]:
np.add(a,b)

In [ ]:
np.subtract(a,b)

In [ ]:
c

In [ ]:
a

In [ ]:
np.add(a,c) # cannot add matrix if dimensions are not the same (shape)

In [ ]:
# Scalar multiplications

np.multiply(3,a)

In [ ]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)

In [ ]:
# The real matrix multiplication (dot product)

np.dot(x,y)

In [ ]:
r = np.array([1,2])
s = np.array([1,2]).reshape(2,1)

In [ ]:
np.dot(r,s)

In [ ]:
f = np.array([1,3,5])
g = np.array([1,2,3,4,5,6]).reshape(3,2)

In [ ]:
np.dot(f,g)

In [ ]:
u = np.array([1,2,3,4,5,3]).reshape(3,2)
v = np.array([2,6,4,8]).reshape(2,2)

In [ ]:
np.dot(u,v)