## Numpy Array Indexing and Selection

In [167]:
import numpy as np

In [168]:
new_arr = np.arange(0,16)

In [169]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [170]:
new_arr[9]

9

In [171]:
new_arr[1:6]

array([1, 2, 3, 4, 5])

In [173]:
new_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
new_arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [175]:
new_arr[:7] = 100 # NumPy arrays has the ability to broadcast

In [176]:
new_arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [177]:
lst = [1,2,3,4,5]

In [178]:
lst[0:3] = 100 # list cannot broadcast

TypeError: can only assign an iterable

## Indexing a 2-D Array (Matrix)

In [179]:
array_2D = np.array([2,4,6,8,10,12,14,16,18])

In [180]:
array_2D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [181]:
array_2D = array_2D.reshape(3,3)

In [182]:
array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [185]:
# grab the value of 2

array_2D[0,0]

2

In [186]:
# grab the first row

array_2D[0]

array([2, 4, 6])

In [187]:
# grab the value of 16

array_2D[2,1]

16

In [188]:
# selecting sub-matrices

# [4, 6]
# [10, 12]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [189]:
array_2D[:2,1:]

array([[ 4,  6],
       [10, 12]])

In [ ]:
# selecting sub-matrices

# [8, 10]
# [14, 16]

In [190]:
array_2D[1:,:2]

array([[ 8, 10],
       [14, 16]])

In [192]:
# selecting sub-matrices

# [4, 6]
# [10, 12]
# [16, 18]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [193]:
array_2D[:,1:]

array([[ 4,  6],
       [10, 12],
       [16, 18]])

In [194]:
# selecting sub-matrices

# [8, 10, 12]
# [14, 16, 18]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [195]:
array_2D[1:,:]

array([[ 8, 10, 12],
       [14, 16, 18]])

In [196]:
big_2D_array = np.arange(50).reshape(5,10)

In [197]:
big_2D_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [198]:
big_2D_array[2:4,3:8]

array([[23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37]])

## Conditional Selection

In [199]:
another_array = np.arange(1,16)

In [200]:
another_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [201]:
another_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [202]:
bool_array = another_array > 5

In [203]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [204]:
another_array[bool_array]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [205]:
another_array[another_array > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Matrix Operations

   - addition
   - subtraction
   - scalar multiplication, matrix multiplication, dot
   - division (there is no such thing!)

In [213]:
a = np.array([3,-4,8,5]).reshape(2,2)
b = np.array([9,-5,2,-6]).reshape(2,2)
c = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [214]:
a

array([[ 3, -4],
       [ 8,  5]])

In [215]:
b

array([[ 9, -5],
       [ 2, -6]])

In [211]:
np.add(a,b)

array([[12, -9],
       [10, -1]])

In [212]:
np.subtract(a,b)

array([[-6,  1],
       [ 6, 11]])

In [216]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [217]:
a

array([[ 3, -4],
       [ 8,  5]])

In [218]:
np.add(a,c) # cannot add matrix if dimensions are not the same (shape)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [228]:
# Scalar multiplications

np.multiply(3,a)

array([[  9, -12],
       [ 24,  15]])

In [226]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)

In [238]:
# The real matrix multiplication (dot product)

np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [229]:
r = np.array([1,2])
s = np.array([1,2]).reshape(2,1)

In [232]:
np.dot(r,s)

array([5])

In [233]:
f = np.array([1,3,5])
g = np.array([1,2,3,4,5,6]).reshape(3,2)

In [234]:
np.dot(f,g)

array([35, 44])

In [236]:
u = np.array([1,2,3,4,5,3]).reshape(3,2)
v = np.array([2,6,4,8]).reshape(2,2)

In [237]:
np.dot(u,v)

array([[10, 22],
       [22, 50],
       [22, 54]])